/**
 * PDF Export Utility
 * Generates PDFs from AI tool outputs using browser print
 */

export interface PDFContent {
  title: string;
  subtitle?: string;
  sections: {
    heading: string;
    content: string | string[];
  }[];
  footer?: string;
}

/**
 * Generate a printable HTML document and trigger browser print dialog
 */
export function exportToPDF(content: PDFContent): void {
  // Create a new window for printing
  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    alert("Please allow popups to export PDF");
    return;
  }

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${content.title}</title>
  <style>
    @page {
      size: letter;
      margin: 1in;
    }
    
    * {
      box-sizing: border-box;
    }
    
    body {
      font-family: Georgia, 'Times New Roman', serif;
      font-size: 12pt;
      line-height: 1.6;
      color: #1a1a1a;
      max-width: 6.5in;
      margin: 0 auto;
      padding: 0;
    }
    
    .header {
      border-bottom: 2px solid #1e3a5f;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    
    h1 {
      font-size: 24pt;
      color: #1e3a5f;
      margin: 0 0 10px 0;
      font-weight: bold;
    }
    
    .subtitle {
      font-size: 14pt;
      color: #666;
      font-style: italic;
    }
    
    h2 {
      font-size: 16pt;
      color: #1e3a5f;
      margin: 25px 0 15px 0;
      padding-bottom: 5px;
      border-bottom: 1px solid #ddd;
    }
    
    p {
      margin: 0 0 15px 0;
      text-align: justify;
    }
    
    ul, ol {
      margin: 0 0 15px 0;
      padding-left: 25px;
    }
    
    li {
      margin-bottom: 8px;
    }
    
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      font-size: 10pt;
      color: #666;
      text-align: center;
    }
    
    .branding {
      margin-top: 10px;
      font-size: 9pt;
      color: #999;
    }
    
    @media print {
      body {
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${escapeHtml(content.title)}</h1>
    ${content.subtitle ? `<p class="subtitle">${escapeHtml(content.subtitle)}</p>` : ""}
  </div>
  
  ${content.sections
      .map(
        (section) => `
    <h2>${escapeHtml(section.heading)}</h2>
    ${formatContent(section.content)}
  `
      )
      .join("")}
  
  <div class="footer">
    ${content.footer ? `<p>${escapeHtml(content.footer)}</p>` : ""}
    <p class="branding">Generated by AI Courses for Adults • aicoursesforadults.com</p>
  </div>
  
  <script>
    window.onload = function() {
      window.print();
      window.onafterprint = function() {
        window.close();
      };
    };
  </script>
</body>
</html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
}

function escapeHtml(text: string): string {
  const div = document.createElement("div");
  div.textContent = text;
  return div.innerHTML;
}

function formatContent(content: string | string[]): string {
  if (Array.isArray(content)) {
    return `<ul>${content.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>`;
  }

  // Convert newlines to paragraphs
  return content
    .split("\n\n")
    .map((para) => `<p>${escapeHtml(para)}</p>`)
    .join("");
}

// Pre-built export functions for each AI tool

export function exportNicheToPDF(niche: {
  name: string;
  targetClient: string;
  problem: string;
  uniqueAngle: string;
  estimatedValue: string;
  firstStep: string;
}) {
  exportToPDF({
    title: niche.name,
    subtitle: "Consulting Niche Profile",
    sections: [
      { heading: "Target Client", content: niche.targetClient },
      { heading: "Problem You Solve", content: niche.problem },
      { heading: "Your Unique Angle", content: niche.uniqueAngle },
      { heading: "Estimated Value", content: niche.estimatedValue },
      { heading: "First Step This Week", content: niche.firstStep },
    ],
    footer: `Generated on ${new Date().toLocaleDateString()}`,
  });
}

export function exportSOWToPDF(sow: {
  projectTitle: string;
  background: string;
  deliverables: string[];
  timeline: { phase: string; description: string; duration: string }[];
  totalDuration: string;
  outOfScope: string[];
}) {
  exportToPDF({
    title: "Statement of Work",
    subtitle: sow.projectTitle,
    sections: [
      { heading: "Background", content: sow.background },
      { heading: "Deliverables", content: sow.deliverables },
      {
        heading: "Timeline",
        content: sow.timeline.map(
          (t) => `${t.phase}: ${t.description} (${t.duration})`
        ),
      },
      { heading: "Total Duration", content: sow.totalDuration },
      { heading: "Out of Scope", content: sow.outOfScope },
    ],
    footer: `Generated on ${new Date().toLocaleDateString()}`,
  });
}

export function exportAgreementToPDF(agreement: {
  projectTitle: string;
  servicesDescription: string;
  paymentTerms: string;
  confidentiality: boolean;
  terminationNotice: string;
}) {
  exportToPDF({
    title: "Consulting Agreement",
    subtitle: agreement.projectTitle,
    sections: [
      { heading: "Services", content: agreement.servicesDescription },
      { heading: "Payment Terms", content: agreement.paymentTerms },
      {
        heading: "Confidentiality",
        content: agreement.confidentiality
          ? "Both parties agree to maintain strict confidentiality of all proprietary information, trade secrets, and sensitive business data shared during the engagement."
          : "Standard confidentiality terms apply.",
      },
      {
        heading: "Termination",
        content: `Either party may terminate this agreement with ${agreement.terminationNotice} written notice.`,
      },
    ],
    footer: `Generated on ${new Date().toLocaleDateString()} • This is a template - please review with legal counsel before use.`,
  });
}

export function exportLinkedInToPDF(post: {
  hook: string;
  body: string;
  lesson: string;
  cta: string;
  hashtags: string[];
}) {
  exportToPDF({
    title: "LinkedIn Post",
    subtitle: "Ready to publish",
    sections: [
      { heading: "Hook", content: post.hook },
      { heading: "Body", content: post.body },
      { heading: "Lesson", content: post.lesson },
      { heading: "Call to Action", content: post.cta },
      { heading: "Hashtags", content: post.hashtags.map((h) => `#${h}`).join(" ") },
    ],
    footer: `Generated on ${new Date().toLocaleDateString()}`,
  });
}
